### ISSUE TITLE
Plugin loading spinner never disappers after it appers

### ISSUE THREAD

**Issue by Matt07211** [jellyfin/jellyfin-plugin-anime#26]
Loading circle visble in this example

![screenshot](https://user-images.githubusercontent.com/12839977/51788390-bc260300-21d1-11e9-89b2-6c968c402b84.png)

The css class in particular (at a quick glance) seems to be `.mdl-spinner__circle `

**Steps to reproduce:**
1. Go to plugin page
2. Go to plugin configuration page (In above image I used the anime plugin as an example)

**Expected behavior**
The loading circle disappear

**Comment by JustAMan** [comment]
@Matt07211 fair point, I moved the issue to the respective repository.
It shouldn't be in the `jellyfin-web`, I agree.

**Comment by StillLoading** [comment]
This is caused by loading and trying to set `#chkMoveExcessGenresToTags` if I recall correctly. Since there is no checkbox with that name it does this infinite loading thing. I removed that option in #23 since it's not even available in [PluginConfiguration.cs](https://github.com/jellyfin/jellyfin-plugin-anime/blob/master/Jellyfin.Plugin.Anime/Configuration/PluginConfiguration.cs)

**Comment by Matt07211** [comment]
This is now closed. 
Fixed by https://github.com/jellyfin/jellyfin-plugin-anime/pull/23
