### ISSUE TITLE
Shall we present AddAnimeGenre as a configuration option?

### ISSUE THREAD

**Issue by Matt07211** [jellyfin/jellyfin-plugin-anime#28]
The option ```<AddAnimeGenre>true</AddAnimeGenre>``` has never been a user configurable option. Shall we make it so? Allow the user to toggle the option, or shall we leave it as is?

**Comment by StillLoading** [comment]
I can see why this was never included as the whole point of having this plugin was to import your anime collection and thus you would want to have a way of filtering by that "type" of content. I guess it all depends on how people use these filters. 
For me personally it could stay that way since I never actually use the filter option. I know my library and use the search function most of the time. But that's just me. Other people might like to have full control over what this plugin (or any plugin) does and does not do.

**Comment by Matt07211** [comment]
> thus you would want to have a way of filtering by that "type" of content. 

I believe it just changes the word from Animation to Anime,  maybe some people would prefer the former over the later so it can fit in with the rest of their cartoons.

Considering we have an option to map the anime from Absolute to SxxExx in the plug-in I don't see how this option should remain hidden

**Comment by StillLoading** [comment]
> I believe it just changes the word from Animation to Anime, maybe some people would prefer the former over the later so it can fit in with the rest of their cartoons.

Okay, that's kind of misleading then. Maybe the option should be more like a selection (like the title language.)? 

e.g.
Anime default genre name:
  ->Anime
  ->Animation
  ->None

**Comment by Matt07211** [comment]
Yeah it would be good like that, also for reference for where I got that info.
https://github.com/jellyfin/jellyfin-plugin-anime/blob/master/Jellyfin.Plugin.Anime/Providers/GenreHelper.cs#L226

**Comment by T0W1** [comment]
+1

**Comment by dkanada** [comment]
@Matt07211 did you still plan on adding this as an option?

**Comment by Matt07211** [comment]
I'd love to, but no clue if or when I can do the task.
